language: node_js
node_js:
- '6'
addons:
  firefox: "latest"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run build
- npm test
deploy:
  provider: releases
  api_key:
    secure: Sfl+X5iDRjsbjn+19I7WWM6cuHnga2deufqnIUCRIj72XG5um6Uq0qIk9AW8G436dATB7hELBOAWOFCUlLK+X7meErt8ew4D6MliGKbEYcQediYhom+CTRYmRvoTshFRPZDLWUieVPM6w6hS44dk0cj1o84WcE+iILBv5vbKQz+/iKallbJCfZ8hH54J2I25UdaPbcAzrRNLyw2TbaeehefNEeB9WPHb8XXF8KhkLtO1yyyiGFtUBN7AV2jPsdMhdZJIdH3NuDUvxMnti+uYJYIt71Mm8fX5cGzstOKBrNU8YJVLEHB5xNj4ozC3tAiKlYq/N4Dx5nw97kKocFJvNetK5i0XAtEYtmv+9bWDBPOx0MvCWipy/ua+UW7gWCB4yqQfRqLCsoGms0np+tWdOs2fm66eOoxgdLgkL5fGb6xuluYJa5ukTa+kW6S6i7xOzcaAVTlFiYdmE5upN8BZ8tmh9o8YqccVcB5WKWOGjig2l+GCVtj4Mr57Hkge6ex0E8Db0hAjkaEemhogvFECeU5vDHsD9Ldzagr8v/c8818mEdoBozcG+eG3qar8q7mmSAmC/qFxoYhNy6oNtxTtAwmZFiOkBuewqEGSD3o4n8oZYNW3yU0WNMvFbxEys+3A7hwplefQNIJG6/ohmQlRoFQ0giYpzwk8jHb2Oy2mot8=
  file: dist/browser/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: imdreamrunner/js-file-worker
    tags: true
